language: cpp
compiler: clang

install:
   - sudo apt-get install libqt4-dev qt4-qmake
   - sudo apt-get install freeglut3-dev

script:
   - qmake -project 'LIBS += -lglut -lGLU -lGL -lm'
   - qmake
   - make
