sudo: required
dist: precise

language: cpp
compiler: clang

install:
   - sudo apt-get install libqt4-opengl qt4-qmake
   - sudo apt-get install freeglut3-dev

script:
   - qmake -project QT+=opengl 'LIBS += -lglut -lGLU -lGL -lm'
   - qmake
   - make
